# Racial Disparities in Policing and Prosecution
### Orange County

### Reminder on how to push to Git
- Make sure in PS C:\Thesis\honors-thesis>
- git status
- git add .
- git commit -m "your message here"
- git push

In [1]:
# Import statements
import pandas as pd
import numpy as np

# Display all columns
pd.set_option('display.max_columns', None)

## Import the RIPA Policing Data
With minor additional pre-processing

In [2]:
# Import 2021-2023 cleaned RIPA policing dataset for Orange County directly from my GitHub
# See "RIPA Cleaning.ipynb" for details on how these were generated from the raw data
ripa_orange_2021 = "https://raw.githubusercontent.com/laurenbchu/honors-thesis/main/data/cleaned_ripa_orange_2021.csv"
ripa_orange_2022 = "https://raw.githubusercontent.com/laurenbchu/honors-thesis/main/data/cleaned_ripa_orange_2022.csv"
ripa_orange_2023 = "https://raw.githubusercontent.com/laurenbchu/honors-thesis/main/data/cleaned_ripa_orange_2023.csv"

ripa_21 = pd.read_csv(ripa_orange_2021)
ripa_22 = pd.read_csv(ripa_orange_2022)
ripa_23 = pd.read_csv(ripa_orange_2023)

In [3]:
# Adding in a YEAR column for ease of use later
ripa_21['YEAR'] = 2021
ripa_22['YEAR'] = 2022
ripa_23['YEAR'] = 2023

In [4]:
# Concatenate all three RIPA datasets together to match the RJA prosecution dataset
policing = pd.concat([ripa_21, ripa_22, ripa_23], axis=0)

# Mapping the codes for race (RAE_FULL) from numbers to race strings
races = {
    1: "Asian",
    2: "Black/African American",
    3: "Hispanic/Latino",
    4: "Middle Eastern/South Asian",
    5: "Native American",
    6: "Pacific Islander",
    7: "White",
    8: "Multiracial"
}

policing['RAE_FULL'] = policing['RAE_FULL'].map(races)

## Import the ACLU Prosecution Data
With minor additional pre-processing

In [5]:
# Import the cleaned ACLU prosecutorial data for Orange County 2021-2023 directly from my GitHub
cleaned_orange_aclu_2021_2023 = "https://raw.githubusercontent.com/laurenbchu/honors-thesis/main/data/cleaned_orange_aclu_2021_2023.csv"
prosecution = pd.read_csv(cleaned_orange_aclu_2021_2023, low_memory=False)

In [6]:
# Adding in a year column for ease of use later
prosecution['filed_date'] = pd.to_datetime(prosecution["filed_date"])
prosecution['year'] = prosecution['filed_date'].dt.year

## Import the Census Data

In [7]:
# Data link
data_url = "https://api.census.gov/data/2020/dec/pl?get=group(P1)&ucgid=0500000US06059"
orange_census = pd.read_json(data_url)
orange_census.columns = orange_census.iloc[0]
orange_census = orange_census.iloc[1:]
orange_census

,GEO_ID,NAME,P1_001N,P1_001NA,P1_002N,P1_002NA,P1_003N,P1_003NA,P1_004N,P1_004NA,P1_005N,P1_005NA,P1_006N,P1_006NA,P1_007N,P1_007NA,P1_008N,P1_008NA,P1_009N,P1_009NA,P1_010N,P1_010NA,P1_011N,P1_011NA,P1_012N,P1_012NA,P1_013N,P1_013NA,P1_014N,P1_014NA,P1_015N,P1_015NA,P1_016N,P1_016NA,P1_017N,P1_017NA,P1_018N,P1_018NA,P1_019N,P1_019NA,P1_020N,P1_020NA,P1_021N,P1_021NA,P1_022N,P1_022NA,P1_023N,P1_023NA,P1_024N,P1_024NA,P1_025N,P1_025NA,P1_026N,P1_026NA,P1_027N,P1_027NA,P1_028N,P1_028NA,P1_029N,P1_029NA,P1_030N,P1_030NA,P1_031N,P1_031NA,P1_032N,P1_032NA,P1_033N,P1_033NA,P1_034N,P1_034NA,P1_035N,P1_035NA,P1_036N,P1_036NA,P1_037N,P1_037NA,P1_038N,P1_038NA,P1_039N,P1_039NA,P1_040N,P1_040NA,P1_041N,P1_041NA,P1_042N,P1_042NA,P1_043N,P1_043NA,P1_044N,P1_044NA,P1_045N,P1_045NA,P1_046N,P1_046NA,P1_047N,P1_047NA,P1_048N,P1_048NA,P1_049N,P1_049NA,P1_050N,P1_050NA,P1_051N,P1_051NA,P1_052N,P1_052NA,P1_053N,P1_053NA,P1_054N,P1_054NA,P1_055N,P1_055NA,P1_056N,P1_056NA,P1_057N,P1_057NA,P1_058N,P1_058NA,P1_059N,P1_059NA,P1_060N,P1_060NA,P1_061N,P1_061NA,P1_062N,P1_062NA,P1_063N,P1_063NA,P1_064N,P1_064NA,P1_065N,P1_065NA,P1_066N,P1_066NA,P1_067N,P1_067NA,P1_068N,P1_068NA,P1_069N,P1_069NA,P1_070N,P1_070NA,P1_071N,P1_071NA,ucgid
1,0500000US06059,"Orange County, California",3186989,NaN,2739808,NaN,1383257,NaN,53842,NaN,38322,NaN,706813,NaN,9035,NaN,548539,NaN,447181,NaN,421361,NaN,14037,NaN,25196,NaN,62878,NaN,3881,NaN,290052,NaN,997,NaN,2526,NaN,342,NaN,3456,NaN,727,NaN,140,NaN,8472,NaN,3701,NaN,4384,NaN,572,NaN,23639,NaN,1769,NaN,1270,NaN,200,NaN,1810,NaN,1538,NaN,191,NaN,9087,NaN,2982,NaN,3740,NaN,302,NaN,110,NaN,17,NaN,148,NaN,94,NaN,133,NaN,8,NaN,38,NaN,67,NaN,28,NaN,107,NaN,1966,NaN,309,NaN,37,NaN,658,NaN,110,NaN,158,NaN,7,NaN,193,NaN,295,NaN,20,NaN,162,NaN,0,NaN,2,NaN,5,NaN,10,NaN,0,NaN,200,NaN,56,NaN,91,NaN,23,NaN,18,NaN,12,NaN,0,NaN,15,NaN,15,NaN,0500000US06059

In [16]:
# Metadata link for defining the columns into readable descriptions
metadata_url = "https://api.census.gov/data/2020/dec/pl/variables.json"
orange_metadata = pd.read_json(metadata_url)

# Turns the metadata into a table for mapping
meta = pd.json_normalize(orange_metadata["variables"])
meta.index = orange_metadata.index

# Select only the P1 labels
p1_meta = meta[meta["group"] == "P1"].copy()
code_to_label = p1_meta["label"].to_dict()

# Drop the columns with "NA"
orange_census = orange_census.loc[
    :, 
    ~orange_census.columns.str.endswith("NA")
]

# Apply mapping to OC data
orange_census_relabeled = orange_census.rename(columns=code_to_label)

## Data Summary

In [17]:
# Policing (RIPA) data

print(f'The RIPA Orange County policing data has', policing.shape[0], f'rows and', policing.shape[1], f'columns')
print(f'\nHere are the number of rows broken down by year:', policing.groupby("YEAR").size())
print(f'\nHere are the number of rows broken down by race:', policing["RAE_FULL"].value_counts())
print(f'\nThe NAs per column in descending order are as follows:\n', policing.isna().sum().sort_values(ascending=False))

The RIPA Orange County policing data has 447512 rows and 16 columns

Here are the number of rows broken down by year: YEAR
2021     90714
2022    189834
2023    166964
dtype: int64

Here are the number of rows broken down by race: RAE_FULL
Hispanic/Latino               192344
White                         156527
Asian                          43551
Black/African American         22186
Middle Eastern/South Asian     20763
Multiracial                     6040
Native American                 3690
Pacific Islander                2411
Name: count, dtype: int64

The NAs per column in descending order are as follows:
 RAE_FULL                  0
REASON_FOR_STOP           0
ADS_SEARCH_PERSON         0
ADS_SEARCH_PROPERTY       0
CED_NONE_CONTRABAND       0
CED_FIREARM               0
CED_AMMUNITION            0
CED_WEAPON                0
CED_DRUGS                 0
CED_ALCOHOL               0
CED_MONEY                 0
CED_DRUG_PARAPHERNALIA    0
CED_STOLEN_PROP           0
CED_ELECT_DEVICE          0
CED_OTHER_CONTRABAND      0
YEAR                      0
dtype: int64

In [18]:
# Prosecution (RJA) data

print(f'The RJA Orange County prosecution data has', prosecution.shape[0], f'rows and', prosecution.shape[1], f'columns')
print(f'\nHere are the number of rows broken down by year:', prosecution.groupby("year").size())
print(f'\nHere are the number of rows broken down by race:', prosecution["canonical_race"].value_counts())
print(f'\nThe NAs per column in descending order are as follows:\n', prosecution.isna().sum().sort_values(ascending=False))

The RJA Orange County prosecution data has 259118 rows and 30 columns

Here are the number of rows broken down by year: year
2021    102847
2022    102820
2023     53451
dtype: int64

Here are the number of rows broken down by race: canonical_race
Latinx    132414
White      88792
Black      15177
Asian      11808
Other      10927
Name: count, dtype: int64

The NAs per column in descending order are as follows:
 statute_level              44894
sentenced_date             35791
category                      72
disposition_description       30
was_convicted                 30
was_filed_by_da                8
referral_date                  0
filed_date                     0
county_id                      0
source_case_id                 0
source_defendant_id            0
source_incident_id             0
disposition_date               0
source_docket_id               0
statute                        0
type                           0
disposition_id                 0
race_id                        0
charge_id                      0
is_attempted                   0
charge_description             0
is_wobbler                     0
canonical_race                 0
is_special_circumstance        0
is_enhancement_charge          0
is_sentencing_charge           0
was_referred_by_lea            0
disposition                    0
is_outcome_unknown             0
year                           0
dtype: int64

## Policing Rates

In [19]:
# Create a column to indicate if any search occurred 
policing["SEARCHED"] = (
    (policing["ADS_SEARCH_PERSON"] == 1) | 
    (policing["ADS_SEARCH_PROPERTY"] == 1)
).astype(int)

# Calculate the search rate by race by year
search_rate_2021 = policing[policing['YEAR'] == 2021].groupby("RAE_FULL")["SEARCHED"].mean()
search_rate_2022 = policing[policing['YEAR'] == 2022].groupby("RAE_FULL")["SEARCHED"].mean()
search_rate_2023 = policing[policing['YEAR'] == 2023].groupby("RAE_FULL")["SEARCHED"].mean()

In [20]:
# Create a column to indicate if any hit occurred 
contraband = [
    "CED_FIREARM", 
    "CED_AMMUNITION", 
    "CED_WEAPON", 
    "CED_DRUGS", 
    "CED_ALCOHOL", 
    "CED_MONEY", 
    "CED_DRUG_PARAPHERNALIA", 
    "CED_STOLEN_PROP", 
    "CED_ELECT_DEVICE", 
    "CED_OTHER_CONTRABAND"
]

policing["HIT"] = (policing[contraband].sum(axis=1) > 0)

# Calculate the contraband hit rate by race by year
hit_rate_2021 = policing[policing['YEAR'] == 2021].groupby("RAE_FULL")["HIT"].mean()
hit_rate_2022 = policing[policing['YEAR'] == 2022].groupby("RAE_FULL")["HIT"].mean()
hit_rate_2023 = policing[policing['YEAR'] == 2023].groupby("RAE_FULL")["HIT"].mean()

In [21]:
# Create one table

policing_tbl = pd.DataFrame({
    "2021 Search Rate": search_rate_2021,
    "2022 Search Rate": search_rate_2022,
    "2023 Search Rate": search_rate_2023,
    "2021 Hit Rate": hit_rate_2021,
    "2022 Hit Rate": hit_rate_2022,
    "2023 Hit Rate": hit_rate_2023,
    "2021 Search Counts": policing[policing['YEAR'] == 2021].groupby("RAE_FULL")["SEARCHED"].count(),
    "2022 Search Counts": policing[policing['YEAR'] == 2022].groupby("RAE_FULL")["SEARCHED"].count(),
    "2023 Search Counts": policing[policing['YEAR'] == 2023].groupby("RAE_FULL")["SEARCHED"].count(),
    "2021 Hit Counts": policing[policing['YEAR'] == 2021].groupby("RAE_FULL")["HIT"].count(),
    "2022 Hit Counts": policing[policing['YEAR'] == 2022].groupby("RAE_FULL")["HIT"].count(),
    "2023 Hit Counts": policing[policing['YEAR'] == 2023].groupby("RAE_FULL")["HIT"].count()
}).rename_axis('Perceived Race')
policing_tbl

,2021 Search Rate,2022 Search Rate,2023 Search Rate,2021 Hit Rate,2022 Hit Rate,2023 Hit Rate,2021 Search Counts,2022 Search Counts,2023 Search Counts,2021 Hit Counts,2022 Hit Counts,2023 Hit Counts
Perceived Race,,,,,,,,,,,,
Asian,0.111322,0.063551,0.063981,0.053381,0.032497,0.029572,5264,20094,18193,5264,20094,18193
Black/African American,0.212733,0.217693,0.219938,0.094720,0.103983,0.097955,3864,9665,8657,3864,9665,8657
Hispanic/Latino,0.220207,0.200304,0.212347,0.114177,0.102534,0.100021,44063,78306,69975,44063,78306,69975
Middle Eastern/South Asian,0.076682,0.055274,0.055184,0.031927,0.021614,0.022097,3508,8883,8372,3508,8883,8372
Multiracial,0.187500,0.120293,0.130754,0.087500,0.069104,0.058801,720,2735,2585,720,2735,2585
Native American,0.005240,0.035147,0.191176,0.003368,0.019274,0.088235,2672,882,136,2672,882,136
Pacific Islander,0.173362,0.177043,0.162637,0.103594,0.078794,0.083516,473,1028,910,473,1028,910
White,0.170580,0.165253,0.163788,0.095854,0.092056,0.090770,30150,68241,58136,30150,68241,58136

## Prosecution Rates

In [22]:
prosecution["was_referred_by_lea"].value_counts()

was_referred_by_lea
True     214224
False     44894
Name: count, dtype: int64

In [23]:
prosecution["was_filed_by_da"].value_counts()

# Because of this result, we cannot compute a disparity rate because there's too little False values

was_filed_by_da
True     259068
False        42
Name: count, dtype: int64

In [24]:
# Calculate conviction rate per race per year
conviction_rates = prosecution.groupby(["canonical_race", "year"])["was_convicted"].agg(["sum", "count"]).reset_index()
conviction_rates.rename(columns={"sum": "number_convicted", "count": "total_cases"}, inplace=True)
conviction_rates["conviction_rate"] = conviction_rates["number_convicted"] / conviction_rates["total_cases"]

conviction_rates

   canonical_race  year number_convicted  total_cases conviction_rate
0           Asian  2021             3233         4578        0.706204
1           Asian  2022             3051         4228        0.721618
2           Asian  2023             2256         3002        0.751499
3           Black  2021             3829         5250        0.729333
4           Black  2022             4828         6609        0.730519
5           Black  2023             2208         3312        0.666667
6          Latinx  2021            38969        50491        0.771801
7          Latinx  2022            42074        54525        0.771646
8          Latinx  2023            20381        27383        0.744294
9           Other  2021             2871         4653        0.617021
10          Other  2022             3079         4271        0.720908
11          Other  2023             1295         2003         0.64653
12          White  2021            27732        37854        0.732604
13          White  2022            24830        33179        0.748365
14          White  2023            13405        17750        0.755211

In [25]:
# Calculate enhancement rate, per race per year
enhancement_rates = prosecution.groupby(["canonical_race", "year"])["is_enhancement_charge"].agg(["sum", "count"]).reset_index()
enhancement_rates.rename(columns={"sum": "number_enhancements", "count": "total_cases"}, inplace=True)
enhancement_rates["enhancement_rate"] = enhancement_rates["number_enhancements"] / enhancement_rates["total_cases"]

enhancement_rates

   canonical_race  year  number_enhancements  total_cases  enhancement_rate
0           Asian  2021                  494         4578          0.107907
1           Asian  2022                  422         4228          0.099811
2           Asian  2023                  246         3002          0.081945
3           Black  2021                  395         5256          0.075152
4           Black  2022                  426         6609          0.064458
5           Black  2023                  151         3312          0.045592
6          Latinx  2021                 4672        50505          0.092506
7          Latinx  2022                 4556        54526          0.083556
8          Latinx  2023                 2085        27383          0.076142
9           Other  2021                  681         4653          0.146357
10          Other  2022                  585         4271          0.136970
11          Other  2023                  165         2003          0.082376
12          White  2021                 2738        37855          0.072329
13          White  2022                 2547        33186          0.076749
14          White  2023                 1138        17751          0.064109

In [26]:
# Table with convictions and enhancements
merged = conviction_rates.merge(
    enhancement_rates[["canonical_race", "year", "number_enhancements", "enhancement_rate"]],
    on=["canonical_race", "year"],
    how="left"
)    

# Convert rates to percentages for readability
merged["conviction_rate"] = pd.to_numeric(merged["conviction_rate"], errors="coerce")
merged["enhancement_rate"] = pd.to_numeric(merged["enhancement_rate"], errors="coerce")
merged["conviction_rate"] = merged["conviction_rate"] * 100
merged["enhancement_rate"] = merged["enhancement_rate"] * 100

# Round to nearest thousandth
merged["conviction_rate"] = merged["conviction_rate"].round(2)
merged["enhancement_rate"] = merged["enhancement_rate"].round(2)

# Rename from rate to percentage
merged = merged.rename(columns={
        "conviction_rate": "conviction_percentage",
        "enhancement_rate": "enhancement_percentage"
})

# Only 2023
merged[merged["year"] == 2023]

,canonical_race,year,number_convicted,total_cases,conviction_percentage,number_enhancements,enhancement_percentage
2,Asian,2023,2256,3002,75.15,246,8.19
5,Black,2023,2208,3312,66.67,151,4.56
8,Latinx,2023,20381,27383,74.43,2085,7.61
11,Other,2023,1295,2003,64.65,165,8.24
14,White,2023,13405,17750,75.52,1138,6.41

In [27]:
# Calculate distribution of types of charges
prosecution["statute_level"].value_counts()

charge_distribution = prosecution.groupby(["canonical_race", "year", "statute_level"]).size().reset_index(name="number_of_cases")
charge_distribution["percent_of_cases"] = charge_distribution.groupby(["canonical_race", "year"])["number_of_cases"].transform(lambda x: x / x.sum())

# Only 2023
charge_distribution[charge_distribution["year"] == 2023].head(9)

   canonical_race  year statute_level  number_of_cases  percent_of_cases
6           Asian  2023        Felony              876          0.397459
7           Asian  2023    Infraction                3          0.001361
8           Asian  2023   Misdemeanor             1325          0.601180
13          Black  2023        Felony             1121          0.432986
14          Black  2023    Infraction                1          0.000386
15          Black  2023   Misdemeanor             1467          0.566628
22         Latinx  2023        Felony             7188          0.332978
23         Latinx  2023    Infraction               24          0.001112
24         Latinx  2023   Misdemeanor            14375          0.665910